 - id: sync_sonoff_states
   alias: Sync Sonoff States
   initial_state: true
   trigger:
     platform: homeassistant
     event: start
   action:
     - service: mqtt.publish
       data:
         topic: "cmnd/sonoffs/state"
         payload: ""
     - service: mqtt.publish
       data:
         topic: "cmnd/sonoffs/POWER"
         payload: ""
     - service: mqtt.publish
       data:
         topic: "cmnd/tasmotas/state"
         payload: ""
     - service: mqtt.publish
       data:
         topic: "cmnd/tasmotas/POWER"
         payload: ""
