homeassistant:
  name: 28 Fieldway
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: !secret trusted_networks
    - type: legacy_api_password
      api_password: !secret http_password

http:
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  server_host: !secret server_host
  server_port: !secret server_port
  base_url: !secret base_url

frontend:
config:
updater:
discovery:
conversation:
logbook:
map:
sun:
ios:
mobile_app:
wake_on_lan:
tts:
  - platform: google_translate
    service_name: google_say
alexa:
  smart_home:
    filter:
      exclude_domains:
        - automation
      exclude_entities:
        - group.all_automations
        - group.all_remotes
        - group.all_devices
        - group.all_switches
        - group.living_room
        - group.bedroom
        - group.family
        - group.mobile_devices
        - binary_sensor.updater

recorder:
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    domains:
      - sun
      - sensor
history:
  exclude:
    domains:
      - sun
      - sensor

mqtt:
  !secret mqtt

person: !include person.yaml

media_player: !include media_player.yaml
switch: !include switch.yaml
apple_tv: !include apple_tv.yaml
sensor: !include sensor.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
